application:
 thread.count: 100
spring: 
    datasource: 
      database: ORACLE
      url: jdbc:oracle:thin:@apsdb-reengineering.cjqj4gfuhy2n.us-east-1.rds.amazonaws.com:1521:APSDB
      userName: stage1
      password: WZPGmzhc5273#%^
      showSql: true
      driverClassName: oracle.jdbc.driver.OracleDriver
      jpaDialect: org.hibernate.dialect.Oracle10gDialect
      generateDDL: false
      connectionPoolSize: 15
      hikari.connection-timeout: 60000
      hikari.maximum-pool-size: 5
er-service: http://ec2-54-174-170-21.compute-1.amazonaws.com/entity-resolution-service/v1/resolveEntity?resolverType=zentity

logging:
  level:
    root: INFO
  file: ingestor.log    
  pattern:
   console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} ${spring.application.name} %-5level [%thread]  %logger{15} - %msg%n'      
